spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Marsor/config_repo.git
          basedir: ./basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"